# Generated by Django 3.2.6 on 2021-09-11 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habilidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidadesuser',
            name='user_habil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='habilidadesuser',
            name='porcen_habil',
            field=models.IntegerField(default=0, max_length=2, verbose_name='Porcentaje de Habilidad'),
        ),
    ]
